baseurl = "http://fradev.de/"
title = "#FRADEV"
languageCode = "en-us"
theme = "vec"
paginate = 10

[menu]
  [[menu.main]]
    name = "chat"
    weight = 0
    url = "https://fradev.herokuapp.com/"
  [[menu.main]]
    name = "jobs"
    weight = 1
    url = "https://fradevjobs.de"
  [[menu.main]]
    name = "devs"
    weight = 2
    url = "/devs"

[params]
  Keywords = "frankfurt,ffm,dev,developers"
  Description = "The Frankfurt Developers Community landing page"
  Avatar = "img/avatar.jpg"
  SelfIntro = "Welcome to the Frankfurt Developers Community"
  SubText = "Slack, Meetups, Jobs & Cod"
  Email = "hello@fradev.de"

  GithubID = "fradevhq"