baseurl = "http://fradev.de/"
title = "#FRADEV"
theme = "coder"

languageCode = "en-us"

paginate = 10
canonifyurls = true

[params]
    author = "Frankfurt Developers Community"
    description = "The Frankfurt Developers Community landing page"
    keywords = "frankfurt,ffm,dev,developers"
    info = "Slack, Meetups, Jobs & Code"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/fradevhq/"

[menu]
  [[menu.main]]
    name = "Chat"
    weight = 1
    url = "https://fradev.herokuapp.com/"
  [[menu.main]]
    name = "Jobs"
    weight = 2
    url = "https://fradevjobs.de"
  [[menu.main]]
    name = "Devs"
    weight = 3
    url = "/devs"